services:
  # Web Service (Streamlit App)
  web:
    build: .
    expose:
      - "8088"
    environment:
      - STREAMLIT_SERVER_PORT=8088
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    networks:
      - app-network

  # NGINX Reverse Proxy with Keycloak Auth
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - app-network
    depends_on:
      - web

networks:
  app-network:
    driver: bridge